export PATH=$HOME/bin:/usr/local/bin:/opt/DataGrip-2019.2.4/bin:$PATH

export TZ=/Europe/Moscow

export TERM=xterm-256color
export EDITOR=/bin/nvim

export ZSH=$HOME/.oh-my-zsh

export TEXMFHOME=~/.texmf

ZSH_THEME=powerlevel10k/powerlevel10k

plugins=(
	git

	zsh-syntax-highlighting
	#fast-syntax-highlighting
	colored-man-pages_mod

	fzf-z

    #vi-mode
    #history-substring-search

	gitignore
)

source $ZSH/oh-my-zsh.sh

source ~/.pl9k.zshrc

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

# dircolors from LS_COLORS
eval $(dircolors -b $HOME/.dircolors)

# zsh autocomplete with dircolors
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit

source ~/.fzf.zsh

alias ls='exa -g -G -h'
alias la='ls -a'
alias ll='ls  -l'
alias l='ll  -a'
alias lt='ls --tree --level=2'

alias tmux='env TERM=screen-256color tmux'

